server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:procdb
    username: sa
    password: as
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  kafka:
    server: "localhost:9092"
    topic: "block"
    consumer:
      group-id: "app.1"

security:
  role: ATM
